### ISSUE TITLE
Possible Bug in orth_dist

### ISSUE THREAD

**Issue by ofsoundof** [samaonline/Orthogonal-Convolutional-Neural-Networks#1]
Hi,
There might be a bug in the following line of `orth_dist`.
https://github.com/samaonline/Orthogonal-Convolutional-Neural-Networks/blob/eb0cd737267e4f61593ca5291a137e2c86d80e8d/imagenet/utils.py#L37
The center of the `target` tensor should be an identity matrix. When `stride = 1`, should it be `target[:,:,2,2] = torch.eye(o_c).cuda()`.

**Comment by samaonline** [comment]
Thank you! I hardcode in the old version so it might not work for all situations. It's fixed now!
