### ISSUE TITLE
Request ResNet18 code

### ISSUE THREAD

**Issue by hchoi71** [samaonline/Orthogonal-Convolutional-Neural-Networks#2]
Hello, 

I found that the ResNet34 and ResNet50 are available through this git repo, but I'm still wondering if you can upload ResNet18 case as well so that I can reproduce the ResNet18 results accordingly. 

Thanks

**Comment by samaonline** [comment]
Yes we do! Will work on updating it after 6/3. Stay tuned.

**Comment by hchoi71** [comment]
Thanks a lot

2020년 5월 27일 (수) 오후 8:34, Peter Wang <notifications@github.com>님이 작성:

**Comment by samaonline** [comment]
Updated, see [here](https://github.com/samaonline/Orthogonal-Convolutional-Neural-Networks/blob/master/imagenet/main_orth18.py)
