### ISSUE TITLE
cifar100 resnet18 exps

### ISSUE THREAD

**Issue by kartikgupta-at-anu** [samaonline/Orthogonal-Convolutional-Neural-Networks#6]
Can you please share for which layers did you do orthogonal regularization for resnet18 models trained on cifar100 and imagenet?
Would be great if you share the code snippet.
Also I dont understand why you dont do orthogonal regularization for conv2 in resnet34 (model provided) and last fc layer?

**Comment by samaonline** [comment]
See [here](https://github.com/samaonline/Orthogonal-Convolutional-Neural-Networks/issues/2).

Empirically we found additional regulation on conv2 gives slightly lower accuracy. We have not experimented constraining orthogonality on the last fc layer, as it is not conv-orthogonality. Some previous works found it might be helpful to regularize that layer.
