### ISSUE TITLE
Request: Filter similarity code

### ISSUE THREAD

**Issue by erobic** [samaonline/Orthogonal-Convolutional-Neural-Networks#7]
Hi,

I am interested in the orthogonality constraint proposed in the paper. Would it be possible to release the code to compute filter similarities, so that I could evaluate its efficacy?

**Comment by samaonline** [comment]
We are using the [guided back-propagation code](https://github.com/utkuozbulak/pytorch-cnn-visualizations) here. Please use this code to run the result and let us know if any question. More details can also be found in the [supplementary materials](https://arxiv.org/pdf/1911.12207.pdf).
