### ISSUE TITLE
reproduction results are bad

### ISSUE THREAD

**Issue by bokveizen** [samaonline/Orthogonal-Convolutional-Neural-Networks#9]
Dear authors,
I tried to reproduce your results by your code, but the results are bad (e.g., ResNet34, only 90.00 top-5 acc.), and I noticed that in the CVPR paper you mentioned that the regularization rate is 0.01 but in the readme here you use 0.5. Could you check? Thanks!

**Comment by samaonline** [comment]
Hi, the top-5 error for resnet34 should be around 7.9.
We did some fine-tuning of the regularization rate, so what shows here may not exactly match what's reported in the paper. I would suggest trying tuning the regularization rate as well.
Another trick is that you could try divide each regularization loss by the size of the input tensor. We find it empirically useful, as it eliminates the imbalance of different tensor size.
Thank you!

**Comment by bokveizen** [comment]
Thanks! But could you provide the exact code you used when you got the results reported in the paper?
